### ISSUE TITLE
Unauthenticated users security

### ISSUE THREAD

**Issue by case-eee** [NicoleKMarino/westeros_outfitters#66]
Background: An unauthenticated user and their abilities
      As an Unuthenticated User
      I cannot view another user's private data, such as current order, etc.
      I should be redirected to login/create account when I try to check out.
      I cannot view the administrator screens or use administrator functionality.
      I cannot make myself an administrator.

**Comment by zackforbing** [comment]
can you clarify what you mean by Unauthenticated User? the way that's phrased makes it sound like just a user that has not logged in, ie, a visitor.

**Comment by case-eee** [comment]
Yup, it's a visitor!
